[package]
name = "chrono-judge-projects-tests"
version = "0.1.0"
edition = "2024"
publish = false

[dev-dependencies]
chrono-judge-projects = { path = "../judge-projects" }
chrono-harness = { path = "../runner" }
chrono-judge-registration = { path = "../judge-registration" }
chrono-judge-filemap = { path = "../judge-filemap" }
serde_json = "1"
tempfile = "3"
chrono-judge-routes = { path = "../judge-routes" }
