[package]
name = "chrono-judge-workflow"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
test = false
doctest = false

[[bin]]
name = "chrono-judge-workflow"
path = "src/main.rs"
test = false
bench = false

[dependencies]
chrono-harness = { path = "../runner" }
chrono-judge-registration = { path = "../judge-registration" }
chrono-judge-filemap = { path = "../judge-filemap" }
chrono-judge-routes = { path = "../judge-routes" }
chrono-judge-projects = { path = "../judge-projects" }
serde_json = "1"
time = { version = "0.3", features = ["parsing"] }

[profile.dev.package.sha2]
opt-level = 3
